services:
  - type: web
    name: shop
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: JDBC_DATABASE_URL
        fromService:
          type: pserv
          name: shop-postgres
          property: connection_string
      - key: DB_USERNAME
        fromService:
          type: pserv
          name: shop-postgres
          property: username
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: shop-postgres
          property: password
      - key: PORT
        value: "10000"

  - type: pserv
    name: shop-postgres
    plan: free
    region: oregon
    ipAllowList: []
